"use client";

import { useState, useTransition } from "react";
import { updateSettlementStatus } from "@/lib/actions";
import type { Settlement, SettlementStatus } from "@/lib/data";
import { publishDataChange } from "@/lib/live-sync";

function formatMoney(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value); }
const labels: Record<SettlementStatus, string> = { pending: "Pending", advertiser_paid: "Advertiser Paid", owner_payable: "Owner Payable", owner_paid: "Owner Paid" };
const styles: Record<SettlementStatus, string> = { pending: "bg-amber-50 text-amber-700", advertiser_paid: "bg-cyan-50 text-cyan-700", owner_payable: "bg-violet-50 text-violet-700", owner_paid: "bg-emerald-50 text-emerald-700" };

export function SettlementRow({ settlement, billboardName, advertiserName }: { settlement: Settlement; billboardName: string; advertiserName: string }) { const [status, setStatus] = useState(settlement.status); const [message, setMessage] = useState(""); const [isPending, startTransition] = useTransition(); function change(next: SettlementStatus) { setMessage(""); startTransition(async () => { try { const updated = await updateSettlementStatus(settlement.slotId, next); setStatus(updated.status); setMessage("Saved"); publishDataChange("settlement"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update settlement."); } }); } return <div className="grid gap-4 border-b border-slate-100 p-5 last:border-b-0 md:grid-cols-[minmax(180px,1.3fr)_minmax(150px,1fr)_repeat(4,minmax(110px,0.8fr))_170px] md:items-center"><div><p className="text-sm font-bold">{billboardName}</p><p className="mt-1 text-xs text-slate-400">{advertiserName} · {settlement.slotId}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-bold ${styles[status]}`}>{labels[status]}</span><Money label="Clearing" value={formatMoney(settlement.clearingPrice)} /><Money label="Fee" value={formatMoney(settlement.platformFee)} /><Money label="Advertiser due" value={formatMoney(settlement.advertiserAmountDue)} /><Money label="Owner payable" value={formatMoney(settlement.ownerAmountPayable)} /><div className="flex items-center gap-2"><select value={status} onChange={(event) => change(event.target.value as SettlementStatus)} disabled={isPending} className="w-full rounded-lg border border-slate-200 bg-white px-2 py-2 text-xs font-bold outline-none"><option value="pending">Pending</option><option value="advertiser_paid">Advertiser Paid</option><option value="owner_payable">Owner Payable</option><option value="owner_paid">Owner Paid</option></select>{message && <span role="status" className="text-[10px] font-semibold text-emerald-600">{message}</span>}</div></div>; }
function Money({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-slate-900">{value}</p></div>; }
