"use client";

import { useState, useTransition } from "react";
import type { PlaybackStatus } from "@/lib/data";
import { acknowledgePlayback, type PlaybackAcknowledgement } from "@/lib/actions";
import { publishDataChange } from "@/lib/live-sync";

const labels: Record<PlaybackStatus, string> = { scheduled: "Scheduled", playing: "Playing", completed: "Completed", failed: "Failed" };
const styles: Record<PlaybackStatus, string> = { scheduled: "bg-violet-50 text-violet-700", playing: "bg-cyan-50 text-cyan-700", completed: "bg-emerald-50 text-emerald-700", failed: "bg-red-50 text-red-700" };
const deliveryLabels: Record<string, string> = { delivered: "Delivered", failed: "Delivery failed", pending: "Delivery pending" };
const deliveryStyles: Record<string, string> = { delivered: "bg-emerald-50 text-emerald-700", failed: "bg-red-50 text-red-700", pending: "bg-amber-50 text-amber-700" };

export function ProofOfPlay({ slotId, status, plannedStartAt, plannedEndAt, playbackTimestamp, failureReason, deliveryStatus, deliveryDetail }: { slotId: string; status: PlaybackStatus; plannedStartAt: string; plannedEndAt: string; playbackTimestamp?: string; failureReason?: string; deliveryStatus?: string; deliveryDetail?: string }) {
  const [currentStatus, setCurrentStatus] = useState(status); const [timestamp, setTimestamp] = useState(playbackTimestamp); const [reason, setReason] = useState(failureReason ?? ""); const [message, setMessage] = useState(""); const [isPending, startTransition] = useTransition();
  function acknowledge(nextStatus: PlaybackAcknowledgement) { setMessage(""); startTransition(async () => { try { const playback = await acknowledgePlayback(slotId, nextStatus, reason); setCurrentStatus(playback.status); setTimestamp(playback.playbackTimestamp); setMessage("Playback acknowledgement recorded."); publishDataChange("playback"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to record acknowledgement."); } }); }
  const deliveryBlocked = deliveryStatus === "failed";
  return <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-600">Proof of play</p><h2 className="mt-1 text-lg font-bold">Simulated screen acknowledgement</h2></div><div className="flex gap-2">{deliveryStatus && <span className={`rounded-full px-3 py-1.5 text-xs font-bold ${deliveryStyles[deliveryStatus] ?? "bg-slate-50 text-slate-600"}`}>{deliveryLabels[deliveryStatus] ?? deliveryStatus}</span>}<span className={`rounded-full px-3 py-1.5 text-xs font-bold ${styles[currentStatus]}`}>{labels[currentStatus]}</span></div></div>{deliveryDetail && <p className="mt-3 text-xs font-semibold text-slate-500">Delivery: {deliveryDetail}{deliveryStatus === "pending" && <a href={`/api/playback/${slotId}/manifest`} className="ml-2 font-bold text-cyan-700 underline">Download USB manifest</a>}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-3"><Info label="Planned start" value={new Date(plannedStartAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })} /><Info label="Planned end" value={new Date(plannedEndAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })} /><Info label="Playback timestamp" value={timestamp ? new Date(timestamp).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not acknowledged"} /></div>{currentStatus === "failed" && <p className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Failure reason: {reason}</p>}{deliveryBlocked && <p className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700">Delivery failed — resolve delivery before acknowledging playing/completed.</p>}<div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => acknowledge("playing")} disabled={isPending || currentStatus === "completed" || deliveryBlocked} className="rounded-xl border border-cyan-200 px-3 py-2 text-xs font-bold text-cyan-700 disabled:opacity-40">Acknowledge playing</button><button type="button" onClick={() => acknowledge("completed")} disabled={isPending || currentStatus === "completed" || deliveryBlocked} className="rounded-xl bg-emerald-500 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Acknowledge completed</button><input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Failure reason" className="min-w-40 rounded-xl border border-slate-200 px-3 py-2 text-xs outline-none" /><button type="button" onClick={() => acknowledge("failed")} disabled={isPending || !reason.trim() || currentStatus === "completed"} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-700 disabled:opacity-40">Report failed</button></div>{message && <p role="status" className="mt-3 text-xs font-semibold text-slate-500">{message}</p>}</section>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xs font-bold text-slate-800">{value}</p></div>; }
